# Generated by Django 5.1.5 on 2025-01-27 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_year',
        ),
        migrations.AddField(
            model_name='driver',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APRV', 'Approved'), ('RJCT', 'Rejected')], max_length=20)),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='driver_documents/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('registration_number', models.CharField(max_length=50)),
                ('insurance_number', models.CharField(max_length=50)),
                ('insurance_expiry_date', models.DateField()),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.driver')),
            ],
        ),
    ]
