# Generated by Django 5.1.5 on 2025-01-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_driver_vehicle_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('DL', "Driver's License"), ('INS', 'Insurance'), ('ID', 'Identification Card')], default='DL', max_length=100),
        ),
    ]
