# Generated by Django 5.0 on 2025-01-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_created_at_user_updated_at_alter_driver_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
