# Generated by Django 5.1.5 on 2025-01-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('RIDER', 'Rider'), ('DRIVER', 'Driver')], default='RIDER', max_length=6),
        ),
    ]
