# Generated by Django 5.1.5 on 2025-01-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='user',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Rider',
        ),
    ]
